name: 'test'
on: [pull_request]
jobs:
    test:
        name: test
        runs-on: ubuntu-latest

        steps:
            - name: Step 1 - info
              run: echo "${{ github.event_name }}  ${{ github.ref}}, ."
